language: python
python:
- '3.6'
cache: pip
install:
- pip install requests
script:
- python update_readme.py


# S: Build Lifecycle
after_script:
  - git init
  - git config user.name "MarkWh1te"
  - git config user.email "iamwh1temark@outlook.com"
  - git add .
  - git commit -m "Update docs"
  # - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
  - git remote set-url --push origin "https://${GH_TOKEN}@${GH_REF}"
  - git push origin master

# E: Build LifeCycle



env:
  global:
    secure: s9q7lqVkkf52fqp3u5uw+q3mrWgY8QgC4mAhCSksO/xrgooAYZJJZZDFtjFNgbkW9NcVYhmFrxO9owJOTzZFryVfty2w/HVUMiEViakOY7FZQ9HO/Ei3n4awfkWKTF1Hbiz5o4oQErY51+HdITbnbX3lQeg575QiLx6rHk9xPZSUdo8jgTmWAHn6KIOwKVOMre+piMcBVo4IoUqgJTSG3c9fcChvfFvTPtiXHnP41Fmxxo4Dkdvqbne+RQjcdFwRDHR0Z6IGDhypXCidOOHrN5UcYwN2asi7xppCcTQRLdlNdbNbG7cpwoMHPF2aFIZPfxEqvABYnqfO0VHtmaHxmJtchtQeJUTQuyoUPGNUv/rK57+urUuOut6iG9Zx7Ik6MAA5Z+qxbUQwjyZ5Ars1BZiDQbxQkbJ7qTas67P/dNzqF9iEDj6FteAILVZJFN6paWaTxpeYgIN91fkDhknuMhbboRjlfW5IttcyEBpVxrXMBsR1uKUCHWhB1G/qViiUSZ2ZrY6FQUP3ANmqRiDLqlL8CzUiHXU0UCE6l5/bpqGMcP/IOqojUKMbVBoYHAphGpjXwoNaCjpB6utQVWHrubgzaCUqwaaJssutVCu+i4sz1brUtLlM/zgNsnCAhehtPlwnbELCdAwIBNTvrUCEwa5dtD87UbVaT4/9RAGZX6o=
    GH_REF: github.com/MarkWh1te/leetcode.git

branches:
  only:
    - master
